### ISSUE TITLE
Digital Publishing menu not showing in Wordpress after installation

### ISSUE THREAD

**Issue by sawafiri** [StudioMercury/digital-publishing-tools-for-wordpress#11]
hello there, we have Wordpress 4.3, tried installing the 2.0.1 plugin, and after successful installation, nothing basically happens!

The plugin shows as installed in the plugin menu, but no digital publishing menu shows on the main wp menu, and there seems to be no way of accessing it!

**Comment by StudioMercury** [comment]
The account you are logged in as in Wordpress, is it an Admin account? Currently, you must be an admin in order to see the digital publishing menu item. It's on our roadmap to allow other user roles to use the plugin and only show the API key for administrators. 

If you are an administrator and you are still unable to find the Digital Publishing menu please attach screenshot here of what your dashboard looks like so we can investigate further.

Thank you,
Studio Mercury

**Comment by feale** [comment]
Hi, 
Please, I have a similar problem, even admin account I dont see all menu options in plug-in

![error-projects3](https://cloud.githubusercontent.com/assets/1869626/10045309/1732c1ce-61d8-11e5-894d-0c679fd9e323.jpg)

**Comment by StudioMercury** [comment]
Hi @feale, 

Currently the plugin only has the following menu options:
- Articles
- Settings
- About
- DPS Portal

Collection support and DPS 1.0 support are coming in a future release. 

We just committed an update to the web site that includes screenshots with the current navigation.

Thank you,
Studio Mercury

**Comment by StudioMercury** [comment]
Hi @feale, 

Currently the plugin only has the following menu options:
- Articles
- Settings
- About
- DPS Portal

Collection support and DPS 1.0 support are coming in a future release. 

We just committed an update to the web site that includes screenshots with the current navigation.

Thank you,
Studio Mercury

**Comment by sawafiri** [comment]
Hi, I have downloaded and updated the plugin using the latest update, but still the plugin does not show on the main WP menu, even though it was successfully installed and activated.

I tried accessing the plugin file directly and got the following error

"DPSFA - Loading CMS: Failed. Requires wordpress v3.5 but found v"

My wordpress version is 4.3.1

**Comment by StudioMercury** [comment]
Hi @sawafiri, we just published an update to the plugin this afternoon. We think this may solve the version issue are running into. Would you update the plugin and try again and let us know if this issue has been resolved?

Thank you,
Studio Mercury
