### ISSUE TITLE
Failed. Could not perform action (push_entity). One of the parameters was invalid.

### ISSUE THREAD

**Issue by haemeulrich** [StudioMercury/digital-publishing-tools-for-wordpress#12]
I have still problems with the connection to the DPS. When I use "Update all" out of the "Cloud" menu I get the following error (I'm not sure if this has anything to do with the issue here: https://github.com/StudioMercury/digital-publishing-tools-for-wordpress/issues/9):

---

Failed. Could not perform action (push_entity). One of the parameters was invalid. [ Show Raw Response ]

Headers
HTTP/1.1 400 Bad Request
 Access-Control-Allow-Origin: *
 Access-Control-Expose-Headers: Link
 Content-Type: application/json;charset=UTF-8
 Date: Mon, 14 Sep 2015 09:51:46 GMT
 Server: APIP
 x-dps-request-id: 7325f789-3830-4fd6-bd23-b1ad899e277e
 Content-Length: 1075
 Connection: keep-alive

Body
{"code":"EntityFailedSchemaValidationException","message":"error: instance failed to match at least one required schema among 2\n level: \"error\"\n schema: {\"loadingURI\":\"#\",\"pointer\":\"/properties/authorUrl\"}\n instance: {\"pointer\":\"/authorUrl\"}\n domain: \"validation\"\n keyword: \"anyOf\"\n nrSchemas: 2\n reports: {\"/properties/authorUrl/anyOf/0\":[{\"level\":\"error\",\"schema\":{\"loadingURI\":\"#\",\"pointer\":\"/properties/authorUrl/anyOf/0\"},\"instance\":{\"pointer\":\"/authorUrl\"},\"domain\":\"validation\",\"keyword\":\"type\",\"message\":\"instance type (string) does not match any allowed primitive type (allowed: [\\"null\\"])\",\"found\":\"string\",\"expected\":[\"null\"]}],\"/properties/authorUrl/anyOf/1\":[{\"level\":\"error\",\"schema\":{\"loadingURI\":\"#\",\"pointer\":\"/properties/authorUrl/anyOf/1\"},\"instance\":{\"pointer\":\"/authorUrl\"},\"domain\":\"validation\",\"keyword\":\"format\",\"attribute\":\"uri\",\"message\":\"string \\"Author URL\\" is not a valid URI\",\"value\":\"Author URL\"}]}\n\n"}

URL
https://pecs.publish.adobe.io/publication/cc9129fa-3d33-4cbe-ae1f-0b9f0106891b/article/montag-14-september-1107-uhr;version=1442222998959

**Comment by haemeulrich** [comment]
I tried the whole stuff on another WordPress installation at another hosting provider. It is running now. The issue now is that the articles are empty. Do you have a hint for this?

**Comment by feale** [comment]
Please, the same problem it have happened with me.

**Comment by StudioMercury** [comment]
@haemeulrich @feale, we just pushed a new update to the plugin this afternoon v2.0.6. Please update the plugin (making sure you also re-transfer the publish-templates directory if you moved it to your active template folder)

In addition in the Wordpress backend please click Settings > Permalinks then click the Save Changes button. The error above sounds like it may be an issue with permalink.

All our best,
-Studio Mercury

**Comment by StudioMercury** [comment]
@haemeulrich @feale, you'll also want to check the article properties and look at the `Author URL` under the article metadata. Please make sure it's a valid URL before updating the article in DPS.

**Comment by jeffreyflores** [comment]
using v2.0.6 and I'm also getting this same error return when trying to "Create in the cloud".
![screen shot 2015-10-13 at 4 10 33 pm](https://cloud.githubusercontent.com/assets/1922564/10466810/308e92aa-71c4-11e5-9053-4f6081a0cacf.png)

**Comment by Luci2015** [comment]
Hi, 
sometimes I get this too, but I identified that it's coming more often because of the keywords already existing.
What I do is to Sync the article first (this will bring up the keywords), then remove the default ones.
When I'm happy with the metadata and image I click Create to the cloud.
@StudioMercury : imho, these keywords should be visible from the start, right?

**Comment by StudioMercury** [comment]
@Luci2015 @jeffreyflores We've updated this bug in 2.0.7 and as of 2.0.7 we've pushed the changes to the official WP plugin portal. From now on you should see updates for the plugin in your WP plugins section under your WP Admin area. If you don't see 2.0.7 please uninstall the plugin and re-install from the WP plugin portal. You won't lose any information in uninstalling the plugin. 

There was a bug in duplicate keywords. We've now resolved this as of 2.0.7 and you should be able to see all keywords now (internal and external facing keywords).
