### ISSUE TITLE
CSS Font Bundling

### ISSUE THREAD

**Issue by josedesousa** [StudioMercury/digital-publishing-tools-for-wordpress#13]
We've noticed that the plugin is not bundling fonts included in the CSS file. Is there any particular formatting required to ensure that this works correctly?

**Comment by StudioMercury** [comment]
We have a method but it's undocumented. We're pushing an update in the next day that will fix some bugs and expose this new function. We're also updating the article.php with an example of how to use it.

More soon.

**Comment by StudioMercury** [comment]
We just pushed an update today (v2.0.3) that shows how to include font files or any additional assets.
