### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by TimHaslam** [StudioMercury/digital-publishing-tools-for-wordpress#14]
Is the article.php template the only one available? Is it possible to have multiple templates? Is it possible to have a custom template for the navigation?

**Comment by StudioMercury** [comment]
Hi @TimHaslam,

You can make as many templates as you'd like. We have documentation about working with templates on the plugin's web site:
http://studiomercury.github.io/digital-publishing-tools-for-wordpress/

To make your own templates, copy the folder publish-templates from the plugin folder into your active theme folder. Once in your theme’s folder the plugin will look there first when searching for a source of templates.

You can then duplicate article.php and make your own template editing the html to make it your own.

Can you clarify which navigation you are talking about? 
- Studio Mercury

**Comment by TimHaslam** [comment]
I have copied over the folder and the article.php is working great, I'm just wondering how to customize cards/layouts. Is the only way through the DPS admin? 

Is there a way to custom the main left hand menu? I can add the brand image, but that's all?

**Comment by StudioMercury** [comment]
Cards/Layouts should ideally be done in the DPS Portal. This plugin is mainly meant to help streamline content from Wordpress into DPS. Once it's in DPS you can use the DPS portal to manipulate how it looks in the app. 

Currently, you can only customize the brand image in the pull out navigation bar (in the DPS viewer). 
- Studio Mercury

**Comment by TimHaslam** [comment]
If we opt for multiple article templates, how do we determine which one an article will use?

**Comment by StudioMercury** [comment]
There are a few options. Under Settings > Templates you can choose the default template to use. 
You can also open an article then click the Edit menu > then choose Wordpress. Once you're in edit mode you can choose the template using the drop down menu under "Article Template"

**Comment by TimHaslam** [comment]
Brilliant, thank you!
