### ISSUE TITLE
.article is linking css/js/images incorrectly

### ISSUE THREAD

**Issue by jeffreyflores** [StudioMercury/digital-publishing-tools-for-wordpress#15]
Was not in v2.0.1.
Unzipping the .article shows that an extra "/" is prepended to all source files in the HTML. 
Removing the "/" fixes the HTML source paths.

**Comment by StudioMercury** [comment]
Last night we just released a new version v2.0.2. 
Please download that version and try the publish again. 

If you moved the folder publish-templates into your active theme folder make sure you delete it and copy the publish-templates folder from the new v2.0.2 folder.

**Comment by jeffreyflores** [comment]
This bug is for v2.0.2. 
It wasn't present in v2.0.1.

**Comment by StudioMercury** [comment]
Hi @jeffreyflores, we found the bug and just released a new version 2.0.3 to address it.

**Comment by jeffreyflores** [comment]
Looks good, thanks!

**Comment by jeffreyflores** [comment]
tested and can confirm bug fixed.
