### ISSUE TITLE
Empty Settings page

### ISSUE THREAD

**Issue by toby1kenobi** [StudioMercury/digital-publishing-tools-for-wordpress#17]
In WordPress admin, if 'Digital Publishing' is expanded there's a Settings sub-nav item. Clicking on this goes to amostly empty WordPress admin page (/wp-admin/admin.php?page=dps_folio_author_home) that's says 'Settings PAGE' at the top

**Comment by StudioMercury** [comment]
Hi @toby1kenobi,
We're working on either redirecting those options into the plugin or removing them until we implement the "normal" support we have in the General tab in settings. For now just click Digital Publishing and once in the plugin you can then choose Settings and edit the settings directly inside of the plugin.

Thank you,
-Studio Mercury

**Comment by toby1kenobi** [comment]
Ok, thanks for the update

**Comment by StudioMercury** [comment]
Hi @toby1kenobi,

We released an update today 2.0.10, with that update we've taken out the expanded sub-nav. When you click "Digital Publishing" you should now be taken directly into the plugin.

Thank you,
Studio Mercury
