### ISSUE TITLE
WordPress 'Collections' functionality

### ISSUE THREAD

**Issue by toby1kenobi** [StudioMercury/digital-publishing-tools-for-wordpress#18]
There's not much documentation, so I don't know if this should behave any differently, but in WordPress admin under Digital Publishing is a Collections item /wp-admin/edit.php?post_type=dpsfa_collection). This allows the creation of new 'collections', but these don't seem to be usable for anything.

**Comment by StudioMercury** [comment]
@toby1kenobi, 
Collection support is on our roadmap, we'll be removing the "collection" option in our next update until we fully implement collection support.

Thank you,
Studio Mercury

**Comment by toby1kenobi** [comment]
Ok, thanks
