### ISSUE TITLE
No underline in article name

### ISSUE THREAD

**Issue by haemeulrich** [StudioMercury/digital-publishing-tools-for-wordpress#20]
I found that you can't use an underline in the article name. If you use one the article will not be created. Please see also the attachment.
<img width="518" alt="bildschirmfoto 2015-10-02 um 14 16 08" src="https://cloud.githubusercontent.com/assets/7011448/10246292/29553b5e-6910-11e5-95f1-f479000a9ea8.png">

**Comment by StudioMercury** [comment]
@haemeulrich, 
We've got this on our roadmap. It'll be coming in the future. 

More soon!

**Comment by StudioMercury** [comment]
We just released a new version of the plugin. 2.1.0, in this version, article naming is now the same as Adobe's specifications for the naming articles.
