### ISSUE TITLE
Cannot "Create in Cloud" a DPS article which has been imported from a WP post

### ISSUE THREAD

**Issue by jeffreyflores** [StudioMercury/digital-publishing-tools-for-wordpress#21]
Using version 2.0.6 of the plugin, I can no longer successfully use the "Create in Cloud" option in a DPS article which has been imported from a WP post. 

![screen shot 2015-10-05 at 4 03 58 pm](https://cloud.githubusercontent.com/assets/1922564/10291819/d03dffbc-6b79-11e5-98cb-a45226ad1801.png)

![screen shot 2015-10-05 at 4 01 15 pm](https://cloud.githubusercontent.com/assets/1922564/10291823/d43f657e-6b79-11e5-821e-c5dab374f553.png)

I do believe this was working in version 2.0.3 however. I still have articles that I linked this way to the cloud and can unlink and create them in the cloud again with success.

**Comment by StudioMercury** [comment]
Hi @jeffreyflores,
Do you happen to have duplicate keywords? We're working on a fix to catch dupe keywords on the plugin level before they are sent to DPS.

-Studio Mercury

**Comment by jeffreyflores** [comment]
@StudioMercury 
No I don't have anything in the 'internal keywords' field nor the 'keywords' field. I've just noticed now however, that after reverting to v2.0.3 I can only "Create in the Cloud" one article before I get the same error I posted above (trying to 'create in the cloud' a second article). Something to note, I can't actually write anything into the "Internal Keywords" field and save it. This is true for v2.0.3 at least.

**Comment by StudioMercury** [comment]
@jeffreyflores We found the culprit. There were duplicate internal keywords but they weren't showing up in the interface. We've resolved it and you shouldn't see this error anymore. We've also added the plugin into the WP plugin portal so if you open your plugins in WP you should see there's an update to the plugin and be able to automatically update it through WP. We'll be pushing out updates through this method in the future.

**Comment by StudioMercury** [comment]
@jeffreyflores, 
We just pushed 2.0.10 tonight, would you upgrade the plugin and see if this problem still persists?

Thank you,
Studio Mercury

**Comment by StudioMercury** [comment]
@jeffreyflores we've released a major update to the plugin that has better handling for importing and checks for duplicate tags/keywords. This issue should be resolved in the newest version.
