### ISSUE TITLE
Enhancing the import process

### ISSUE THREAD

**Issue by chrishutchinson** [StudioMercury/digital-publishing-tools-for-wordpress#22]
Hey,

When importing a standard WP Post into the Digital Publishing section, I'd like to alter / add the mappings between fields. For example, I'll be registering some custom fields on the Post page to take in some additional data, and I'd like to populate some of the DPS metadata with the values of those fields. Additionally, during import, metadata fields such as "Author" aren't filled out. Having a filter or similar to be able to define these mappings would be really handy!

Is something like this available already, in the pipeline, or easily added? I'm a WP dev so am happy to contribute if required!

**Comment by chrishutchinson** [comment]
Hey @StudioMercury,

Just wanted to check in with this and see what your thoughts were? This is the main thing preventing me from being able to use this plugin at present.

**Comment by StudioMercury** [comment]
@chrishutchinson we're definitely looking into this and adding more ways of customizing the plugin. We're going to add basic support for import options in a coming release. And feel free to contribute any updates / changes to the plugin, it's open for anyone to contribute.

**Comment by chrishutchinson** [comment]
Will do, thanks! I've current hooked into the publish action on the custom post type to do the mapping I need, and have used ACF to register some additional meta fields on the CPT in order to create the interface I need.

Is there a general roadmap available of the features you're looking to add? And, it may be answered as part of that, but any collection / card management planned?

**Comment by StudioMercury** [comment]
@chrishutchinson we just released a new version of the plugin and it has mapping for importing. This gives you a handful of tags and we're going to look at adding new ones in the future.
