### ISSUE TITLE
Articles created from WP do not work on Android devices

### ISSUE THREAD

**Issue by jeffreyflores** [StudioMercury/digital-publishing-tools-for-wordpress#23]
I've noticed that articles created from WP and sent to the Content Producer work fine on iOS devices but get a "Download failed" error on Android devices. However, when I download the article.zip created by the WP plugin onto my Desktop, then use the Adobe 'HTML Article Packager' and reupload, the article works fine for both iOS and Android devices. I did some investigation, and the only difference I could spot was in the manifest.xml being created.

**Comment by StudioMercury** [comment]
@jeffreyflores we're going to look into it. Do you mind shooting us an export of your article.zip? I'd want to take a peak at what might be causing the error in the manifest.xml. You can shoot an e-mail to: developer@smny.us.

**Comment by jeffreyflores** [comment]
@StudioMercury 
Sent an e-mail over just now. These two things are outlined in the e-mail, but here they are again:

In the references to the wp-content folder, there is a leading “/“ there in the SM manifest for the resource href attribute  (line 51)
Vs. no leading “/“ in the ADOBE manifest resource href attribute (line 63).

The fonts in the ADOBE manifest have specific resource types according to type of font 
Vs. "application/octet stream” resource type for all fonts in SM manifest.

**Comment by josedesousa** [comment]
+1 we are also experiencing this issue. Last tested with v2.0.9.

**Comment by jeffreyflores** [comment]
@StudioMercury can you let me know if you've received my emails thus far? Please and thanks. Would really like to help fix this issue.

**Comment by StudioMercury** [comment]
@jeffreyflores we got your emails and put a fix in for packaging article files (there were other issues with the packager too).

We just released an update 2.0.10 with an improvement to the packaging of the article. We updated the way the template. If you look inside the article.php file you'll see we're looking for full paths (or relative paths to the server now). This is part of a larger goal to allow any template (or theme) to be used for creating an article. Relative paths are no longer relative to the article. You can manually specify relative paths in the filter (dpsfa_bundle_article). It's been committed to github but will be available via wordpress's plugin portal within the hour.

**Comment by StudioMercury** [comment]
@jeffreyflores this should be resolved in the newest issue. Please let us know if you still have problems with article files in android.
