### ISSUE TITLE
Article download doesn't work / ZIP file is incomplete

### ISSUE THREAD

**Issue by ghost** [StudioMercury/digital-publishing-tools-for-wordpress#24]
Hi @StudioMercury 
when I download an article from the plugin I get an incomplete zip file. I can't unzip it (error message: "End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.") nor upload it to DPS (error message: "The content is unavailable because there was an error while unzipping the article. [IN024]" ).
The problem seems to be somewhat related to #2 
Thanks a lot for sharing your plugin and helping us out with this issue!

**Comment by StudioMercury** [comment]
@ju21,

We have some follow up questions:
1.) Are you using the default template?
2.) Can you please send us the .zip file that's downloaded? 

Thank you,
Studio Mercury

**Comment by ghost** [comment]
Dear Studio Mercury Team,

attached you can find the requested .zip file. (GitHub digital-publishing-tools-for-wordpress issue #24)

Thank you and have a nice day!

Jonathan Ulrich

**Comment by ghost** [comment]
Hi @StudioMercury 
thanks for your reply.
1.) we are not using the default template but the issue occurs also when selecting it
2.) I sent you a mail with the corresponding .zip file
Thanks again and all the best!

**Comment by StudioMercury** [comment]
@ju21,
The file didn't come through. 
Would you be able to send the file to our e-mail address:  hello@smny.us
Thank you.

**Comment by ju21** [comment]
@StudioMercury FYI: I used the GitHub mail reply first and now sent it again to hello@smny.us Thanks!

**Comment by StudioMercury** [comment]
@ju21, we're not getting your e-mail with the file.
Would you mind putting it on Dropbox or WeTransfer and emailing us a link?

Thank you.

**Comment by ju21** [comment]
@StudioMercury I just sent you the dropbox link to hello@smny.us ... thanks!

**Comment by StudioMercury** [comment]
@ju21,

please also send to: developer@smny.us
we’re unfortunately not seeing any e-mails from you to our hello email account.

You can also paste in the link here, we’ll remove it from this thread.

thank you

**Comment by ju21** [comment]
@StudioMercury just sent it to developer@smny.us

just to make sure here are the links again:

with our template:
https://www.dropbox.com/s/rwdn28hmvu2bhfe/huehnersuppe-mit-gemuese-und-gabelspaghetti_article.zip?dl=0

and with the standard article template:
https://www.dropbox.com/s/9ifxvoxwk1anz4v/huehnersuppe-mit-gemuese-und-gabelspaghetti_article_template.zip?dl=0

**Comment by StudioMercury** [comment]
Thank you @ju21 
We got your e-mail.

**Comment by StudioMercury** [comment]
We just released an update 2.0.10 with an improvement to the packaging of the article. We updated the way the template. If you look inside the article.php file you'll see we're looking for full paths (or relative paths to the server now). This is part of a larger goal to allow any template (or theme) to be used for creating an article. Relative paths are no longer relative to the article. You can manually specify relative paths in the filter (dpsfa_bundle_article). It's been committed to github but will be available via wordpress's plugin portal within the hour.

**Comment by StudioMercury** [comment]
@ju21 We've released an update to the plugin that resolves a number of issues. Problems zipping an article file should be resolved in this update. Any warnings from PHP at the time of bundling were corrupting the zip, we've suppressed these and zipping article files is improved.
