### ISSUE TITLE
WP suggests update to plugin version 2.0.7. but that doesn't work 

### ISSUE THREAD

**Issue by ghost** [StudioMercury/digital-publishing-tools-for-wordpress#25]
Dear @StudioMercury 
WP suggests an automatic update for your plugin to version 2.0.7. but running the update breaks the plugin (I can still see it on the admin menu, but there are no submenu items anymore and nothing happens when I click on it). After turning back to v 2.0.6. it works again, except this issue: #24 
Thanks and have a nice day!

**Comment by StudioMercury** [comment]
@ju21 The submenus were removed to prevent confusion. We're going to add them back in a future version which will allow editing in the native WordPress screens. After you install 2.0.7, you'll need to refresh the page. Then click again on the "Digital Publishing" menu item. This should take you into the plugin screen (https://github.com/StudioMercury/digital-publishing-tools-for-wordpress/raw/master/assets/screenshot-4.png).

**Comment by ghost** [comment]
@StudioMercury Thanks for the quick reply! However, your suggested solution did not solve the problem for me. For some strange reason there is a redirection error after updating and the link in the menu does not work anymore. However, when I directly go to the URL mydomain.com/wp-admin/admin.php?page=dps_folio_author it works and I can use the plugin. It's a workaround, but solves the problem if anyone is experiencing the same issue...

**Comment by StudioMercury** [comment]
@ju21 What about deleting the plugin and re-installing directly from the WordPress plugin portal. It might be that the update from the manual install to the one available from the plugin portal is causing hiccups. I'm curious if you just install directly through the portal if that resolves any issues. We're going to start moving away from the direct download links and start pushing updates through the WP plugin portal.

**Comment by ghost** [comment]
@StudioMercury Deleting and reinstalling the plugin did not help either, but I did find the cause of the problem: It's not your plugin, but the plugin Admin Menu Editor that was causing the weird redirection after the submenus were removed. I changed the settings there and now have direct access again. Now everything works fine except this very important issue: #24 Thanks a lot for your work and quick help!
