### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by zkenstein** [StudioMercury/digital-publishing-tools-for-wordpress#26]
I tried to configure the setting, but on the API tab I got this error at the header:

Failed. Could not perform action (save_settings). SSL certificate problem: unable to get local issuer certificate

Anyone has experienced with this?

Thanks,

**Comment by StudioMercury** [comment]
@zkenstein, would you mind providing a screenshot of where you are seeing this error? That will help us replicate it. Can you also give us more information about the hosting environment you are using?

Thank you,
Studio Mercury

**Comment by zkenstein** [comment]
Hi @StudioMercury no worries, failure came from my server, failed to load .pem certificate file. I will close this
