### ISSUE TITLE
Updating article folio content doesn't work on the first attempt 100% of the time

### ISSUE THREAD

**Issue by jeffreyflores** [StudioMercury/digital-publishing-tools-for-wordpress#29]
![screen shot 2015-10-30 at 4 37 55 pm](https://cloud.githubusercontent.com/assets/1922564/10857456/9826c6f4-7f24-11e5-866c-14dd6a2b1b49.png)

When attempting to update article folio content after a change has been made to article, I always get an error on the DPS Content Producer side though the WP plugin tells me the upload has been successful.
![screen shot 2015-10-30 at 4 39 53 pm](https://cloud.githubusercontent.com/assets/1922564/10857524/eeceff30-7f24-11e5-8ce2-28ad782e63b4.png)

To "remedy" this, I've needed to try to update my article's metadata, which gives me this error 100% of the time:
![screen shot 2015-10-30 at 4 43 05 pm](https://cloud.githubusercontent.com/assets/1922564/10857590/55b70fbc-7f25-11e5-9710-ebbfd0a28547.png)

I then proceed to refresh my page as instructed, and at only that point, I can update article folio content with success.

**Comment by josedesousa** [comment]
+1, having the exact same problem

**Comment by StudioMercury** [comment]
Hi @jeffreyflores, @josedesousa-tcc,

This fix didn't make it in 2.0.10 that we released tonight, however it is coming in the next release which will be a big one.

More soon!

**Comment by josedesousa** [comment]
Happy New Year all!

Just wondering if there was any news on the next big release. Would love to see this issue resolved.

**Comment by StudioMercury** [comment]
Hi José! Happy New Year to you as well! Our team is working on updates to
the plugin during Q1 of 2016. We hope to have a new release soon. Thank
you!!

On Mon, Jan 4, 2016 at 10:12 AM, José De Sousa notifications@github.com
wrote:

> Happy New Year all!
> 
> Just wondering if there was any news on the next big release. Would love
> to see this issue resolved.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StudioMercury/digital-publishing-tools-for-wordpress/issues/29#issuecomment-168702352
> .

## 

Sarah Capers
MERCURY
1133 Broadway Suite 218
New York, NY 10010
310.663.2564
sarah@smny.us

**Comment by josedesousa** [comment]
Hey @StudioMercury,

Just wondering if there was any news on the next release?

**Comment by gmatthews61** [comment]
Having the same problem if i want to update an articles content i have to delete it from Adobe Experience Mobile Manager and push it again through the plugin. or update meta data refresh page and then upload. 

I know both of those a bit annoying so hoping for an update soon.

**Comment by contentkiai** [comment]
Update All will upload the HTML/CSS content, following refresh.

Update Article Folio hasn't worked for me at all. I always have to download, unzip, and upload the .article archive through the AEM GUI on initial upload. For subsequent uploads of the same article, Refresh > Update All always works.

Could there be a bug with the sidecar.xml and content directory in the export? Only the .article file should be uploaded.

---

edit: Was able to successfully use Update Article Folio after first choosing "Create in the Cloud" and then updating article folio without having edited properties or uploaded a thumbnail image. Using browser refresh seems to help with all content saved.

**Comment by StudioMercury** [comment]
We've just released a major update to the plugin. This bug and other versioning bugs should be fixed in this new update. The plugin was pushing the images / metadata first then trying to upload the .article file after the version number had changed. Pushing .article files now work as expected.
