### ISSUE TITLE
"Update in Cloud" dropdown button from "Articles" tab does nothing

### ISSUE THREAD

**Issue by jeffreyflores** [StudioMercury/digital-publishing-tools-for-wordpress#30]
![screen shot 2015-10-30 at 4 49 13 pm](https://cloud.githubusercontent.com/assets/1922564/10857734/3403b3ba-7f26-11e5-9f1d-4eb3033ba509.png)

There is no way to batch update these articles in this case, and you'll have to go in there one by one to update.

**Comment by StudioMercury** [comment]
@jeffreyflores,

This button is a feature we've been working on that isn't quite ready for prime time, it's a bigger lift than what we originally planned. With that said, in the next big update we release the icon will be taken out as we prep the feature for release in the following update.

Thank you,
Studio Mercury
