### ISSUE TITLE
DPS Menu Item Not Showing

### ISSUE THREAD

**Issue by TimHaslam** [StudioMercury/digital-publishing-tools-for-wordpress#32]
The DPS Menu item is not showing in the WP Admin. I am using 2.0.9 and have deactivated and then re-activated the plugin to try to get it to work. 
![screen shot 2015-11-04 at 10 40 43 am](https://cloud.githubusercontent.com/assets/1372810/10946639/9984c54a-82e0-11e5-81f0-c24b064866ec.png)

**Comment by StudioMercury** [comment]
Hi @TimHaslam,

We just released 2.0.10 tonight. Would you mind upgrading to that version, then if you are still unable to see "Digital Publishing" in the left menu please try:
- Ensuring the user account you are logged in to is an Administrator
- Please disable all plugins until you see "Digital Publishing" then re-enable plugins one by one until you find the culprit. 

Thank you,
Studio Mercury

**Comment by TimHaslam** [comment]
Found the problem. It was a plugin conflict. Envato WordPress Toolkit was the culprit in case anyone else has this problem.
