### ISSUE TITLE
Unable to load settings page

### ISSUE THREAD

**Issue by rharvego** [StudioMercury/digital-publishing-tools-for-wordpress#37]
Hello,
I'm a new user, testing this plugin for our company but am unable to get the settings page to load after (what appears to be) a successful installation.  

When I select the Digital Publishing option in the left nav, I get taken to a page that appears to be trying to load something but with an error at the top of the page that says "Failed.  Could not perform action(get_settings)."  Please find screenshot attached.

We are using Media Temple as it was mentioned in the documentation.  

![screen shot 2015-12-14 at 1 51 12 pm](https://cloud.githubusercontent.com/assets/16310583/11821036/1ddcbd04-a32d-11e5-983b-def1378e0856.png)

I was able to install this on my personal hosting account (another Provider) without an issue.  Are there any extra settings I should be looking for?

Thank you for your help,

Roy

**Comment by StudioMercury** [comment]
Hi Roy,

The plugin uses Ajax calls to communicate back and forth with WordPress. It seems PHP is printing an error before it can return a valid response from WP. We’re working on an update to be released in the next couple of weeks that will fix this and disable any php errors during ajax calls. 

In the meantime, you can disable php errors using the steps below:
https://wordimpress.com/php-turn-on-or-off-error-reporting/ https://wordimpress.com/php-turn-on-or-off-error-reporting/

**Comment by rharvego** [comment]
thanks so much for your help!  i've gotten everything and running but when
i create an article and check it w/in the DPS portal, i'm getting an error
saying "Unable to parse the manifest file. [IN014]"

when i look inside the article file, its empty except for the manifest file
which appears to be missing bits.

any suggestions?

**Comment by gmatthews61** [comment]
I'm running into the setup screen issue as well and I turned off the php error reporting - http://www.themesrefinery.net//turn-wordpress-error-reporting/

however i'm still not getting the settings page to run i am on wordpress 4.4 though

keep getting - Failed. Could not perform action (get_settings).

**Comment by rharvego** [comment]
EliteGD, 
FYI, I actually got mine to work by moving to another host (from Media Temple to Hostmonster - it was time to renew anyway and we were able to test and successfully install on their servers.)   Since then, we have been unable to get the plug-in to successfully create the .article files (no errors w/in wordpress but dps saying it doesn't have the file and when i download it, it's missing everything).  I've opened a ticket for this next issue and am waiting...

**Comment by gmatthews61** [comment]
Oh that is rough, yeah i'm trying to get this to work as it would be great for our dps solution i'm going to try on a different hosting platform tomorrow to see if I have any better luck. This one is on a server my company has so i'm not sure what the problem would be but i'll try a shared hosting server that i have an account with.

**Comment by rharvego** [comment]
moving to a new host fixed this for us.  however, as per the StudioMercury Team, there was an issue and a patch was released.  so, i can't be sure which fixed it.  however, it's working and i'm closing this.

thanks everyone!
