### ISSUE TITLE
Enhancement : Add article to a specific Collection

### ISSUE THREAD

**Issue by gmatthews61** [StudioMercury/digital-publishing-tools-for-wordpress#41]
So this isn't really an issue and maybe i just haven't figured it out yet.

Is there anyway with this plugin to add the article to a specific collection? 
As right now I can create articles and send them dps but then I need to add them to a collection so that they can actually be displayed in my app.

**Comment by StudioMercury** [comment]
Hi @EliteGD, 
Currently the plugin doesn't do anything with Collections. We wanted to focus all of our energy on the part of the process that happens from content creation to when the content is uploaded into AEM Mobile.

The plugin's main focus is to help streamline the import and upload of content from Wordpress into AEM Mobile. Once the content is in AEM Mobile a user can then use the AEM Mobile Dashboard to create collections, edit collections and publish. 
- Studio Mercury
