### ISSUE TITLE
Plugin Failed – PHP Error on line 525

### ISSUE THREAD

**Issue by toughmedia** [StudioMercury/digital-publishing-tools-for-wordpress#45]
![bildschirmfoto 2016-02-09 um 19 11 44](https://cloud.githubusercontent.com/assets/2473931/12925942/28290550-cf61-11e5-9b8b-2f949a4ff3ae.png)

**Comment by StudioMercury** [comment]
@toughmedia, it appears to be an issue with your server. I went to your web site and the same error is showing on your public facing site as well:

Strict Standards: Non-static method allow_php_in_posts::option_get() should not be called statically in /home/httpd/vhosts/tafanalo.ch/httpdocs/wordpress/wp-content/plugins/allow-php-in-posts-and-pages/allowphp.php on line 396

Maybe try turning off "Strict Standards". 

All our best,
Studio Mercury
