### ISSUE TITLE
How do you do this?

### ISSUE THREAD

**Issue by kandymagazine** [StudioMercury/digital-publishing-tools-for-wordpress#47]
log into the Adobe Digital Publishing Solution portal and assign the AdobeID (the one assigned to the API) access to the publication you’d like to use. Where in DPS is this done?

**Comment by josedesousa** [comment]
Hi @kandymagazine,

You cannot do this in DPS, instead you need get the details from Adobe directly. The following page should explain the process for you:

https://helpx.adobe.com/digital-publishing-solution/help/integrating-dps.html

**Comment by StudioMercury** [comment]
@kandymagazine I see where you're getting stuck in the docs. That sentence is from the area if you're not seeing any projects in the plugin (or specific ones). If you're not seeing projects or ones that you have set up, you can do the following:

1) Log into the Adobe AEM Mobile dashboard: https://aemmobile.adobe.com (using the login associated with the Adobe API)
2) Click Project settings
3) If you don't see any projects, create one here
4) If you have projects created in your master account but don't see them here, you'll need to log into your master account and grant access to the user associated with the Adobe API Access. You'll then see the project listed in projects under your Adobe API account 
5) Now open the WordPress plugin and open settings. Under the Adobe API tab you should see your publications in this list.
