### ISSUE TITLE
Adobe Experience Manager Mobile - Implications

### ISSUE THREAD

**Issue by josedesousa** [StudioMercury/digital-publishing-tools-for-wordpress#48]
Hello,

I was wondering what implications (if any) exist now that DPS 2015 has been integrated into AEM?

Many thanks,
José

**Comment by StudioMercury** [comment]
There hasn't been any confirmation of the API changing (there may be some endpoint changes in the future but there's no release date for that). We don't see the API drastically changing. The move to AEM doesn't feel like a shift in product capabilities, just bringing the product in line with the AEM umbrella. However, you might want to reach out to your Adobe representative to see if there are implications that might effect you in other areas.
