### ISSUE TITLE
Missing File When Uploading to Cloud or attempting to Download

### ISSUE THREAD

**Issue by kandymagazine** [StudioMercury/digital-publishing-tools-for-wordpress#49]
Receiving this error message which indicates a line of code is missing which is preventing the plug-in from creating the .article file 
Fatal error: Class 'ZipArchive' not found in /wp-content/plugins/digital-publishing/classes/dpsfa-bundlr.php on line 3225

**Comment by StudioMercury** [comment]
This error is happening because you don’t have ZipArchive compiled into php (zip archive class needs to be installed with PHP) see: http://stackoverflow.com/questions/3872555/fatal-error-class-ziparchive-not-found-in
