### ISSUE TITLE
no response from the server

### ISSUE THREAD

**Issue by Luci2015** [StudioMercury/digital-publishing-tools-for-wordpress#5]
Hello,

I'm trying to set up Wordpress 4.3 with this plugin but I'm not getting the Access Token or the Refresh Token even if I provided the correct Adobe Key, Secret, Device ID & Device Token. I have also set up account & project in DPS2015 and associated same user to it as the one for wordpress.
The Save button does not trigger the obtention of the Acces & Refresh Token.

The Refresh list link button has this error in console:
Error: undefined is not a function (evaluating '$scope.settings.get()')      angular.js:11655

Please advise

**Comment by remoblaser** [comment]
Hey Luci2015
Not sure if this helps you too: I had someone with a similar problem and he redownloaded/reinstalled the Plugin and it works fine now.

Cheers!

**Comment by Luci2015** [comment]
Thanks for the idea, remoblaser, but I did that several times and with different versions of Wordpress; still no luck. It has to be some php setting that I've missed, or my server is not configured correctly. I can manually call with Postman the link that is constructed to obtain the Access token and get the result, but no chance through the plugin.

**Comment by StudioMercury** [comment]
@Luci2015 are you still seeing this problem? We're currently looking into this (we've had this pop up in another environment).

**Comment by Luci2015** [comment]
I have just finished installing the new 2.0.1 plugin but still no joy. The Save or Refresh options do not retrieve back an Access Token.
Refresh is giving this in console:
Error: $scope.settings.get is not a function                                angular.min.js:102:325
Save is indeed saving the data, but the object obtained in console is missing multiple data records, including the Access token
I am running Wordpress on Apache with PHP 5.4.42, MySQL 5.5

**Comment by haemeulrich** [comment]
I have installed the 2.0.1 plugin. And when I want to upload an article to the cloud I still get this error:

Headers
HTTP/1.1 401 Unauthorized
 Content-Type: application/json
 Date: Thu, 03 Sep 2015 15:26:07 GMT
 Server: APIP
 X-Request-Id: CqLck19QB1MlDd2HpFeVvwbcgXuKiYv4
 Content-Length: 61
 Connection: keep-alive

Body
{"error_code":"401013","message":"Oauth token is not valid"}

URL
https://pecs.publish.adobe.io/publication/cc9129fa-3d33-4cbe-ae1f-0b9f0106891b/article/test

**Comment by StudioMercury** [comment]
Hi @haemeulrich that error is because your token expired. Try it again (the plugin should try to grab a new one for you). In a next update we'll do this for you seamlessly. For now, you just need to try the push again.

**Comment by haemeulrich** [comment]
OK it does the trick – it is running now – thank you!

**Comment by StudioMercury** [comment]
@haemeulrich great! Glad it's working. In the future, if you get that error (it happens sometimes that your token will expire), just try it again :)

**Comment by haemeulrich** [comment]
Cool, thanks!
One minor thing: When I delete articles the delete dialog isn't disappearing. I have to close it manually and then to refresh the browser…

**Comment by StudioMercury** [comment]
@Luci2015, 
We just released an update to the plugin this afternoon (v2.0.6) if you're still experiencing issues please delete the old plugin and re-install the new one. If you moved the "publish-templates" folder into your active theme folder make sure you replace it with the new one inside of the new plugin as we've changed a few things in article.php.

In addition in Wordpress please go to Settings > Permalinks and then click the Save Changes button. We've noticed that some people find success after doing this.

Thank you,
-Studio Mercury

**Comment by StudioMercury** [comment]
We just released a new version 2.0.10 today. You can update directly from Wordpress if you installed using the plugin through Wordpress.

-Studio Mercury
