### ISSUE TITLE
Problems behind a reverse proxy

### ISSUE THREAD

**Issue by Slydder** [StudioMercury/digital-publishing-tools-for-wordpress#50]
We have a working install of the plugin on multiple production systems but have not been able to get it working in our Dev environment. The Dev server is Apache 2.4 with php 5.6 and all required modules. The reverse proxy is also an Apache 2.4 server that handles all incoming connections and proxies them to the correct backend servers.

The problem we are having is after installing the plugin we enter Company, Adobe Key, Adobe Secret, Device ID and Device Token. Upon clicking "Save" it attempts the "save_settings" function and times out eventually with a 300 status code spit back from Apache.

Will post further info once I debug a bit more.

**Comment by StudioMercury** [comment]
@Slydder, were you able to debug this further? Would you be able to provide us with the returned data from the log and any warnings or errors that pop up in Safari's Debug Mode? 

Thank you,
Studio Mercury

**Comment by StudioMercury** [comment]
@Slydder we just released an update to the plugin. You could try updating it and see if the update resolves the issue. The plugin uses ajax calls so the reverse proxy could be interfering with the ajax calls. If that's the case, you'll want to make sure your settings enable cross domain ajax calls.
