### ISSUE TITLE
Bad Request Exception - Attempting to set a bogus version

### ISSUE THREAD

**Issue by darrinjillson** [StudioMercury/digital-publishing-tools-for-wordpress#51]
I am getting a Bad Request Exception - Attempting to set a bogus version when I try to publish an article to Adobe. Everything else seems to be working fine. Where there a file we need to change a version on?

![badrequestexception](https://cloud.githubusercontent.com/assets/1557143/13855754/447e0580-ec48-11e5-85f4-951c023a7eb8.PNG)

**Comment by darrinjillson** [comment]
This appears to be an issue where something gets updated within the AEM portal so the information coming from wordpress is out of date.

**Comment by StudioMercury** [comment]
@darrinjillson we've just released a major version of the plugin. This new version handles article versions better. Install the update and see if this helps resolve the error.
