### ISSUE TITLE
Is the .article supposed to upload to the cloud with the meta data?

### ISSUE THREAD

**Issue by kaynenh** [StudioMercury/digital-publishing-tools-for-wordpress#52]
I'm just curious if the .article file is supposed to be passed along to AEM content or if the process is supposed to be: 1. download the article file and then 2. upload to an AEM article? The meta data, titles, etc. all get pushed to AEM correctly, so I'm assuming the functionality just doesn't exist yet or maybe I'm missing something. Thank you in advance!

**Comment by StudioMercury** [comment]
@kaynenh The process should be as follows:
1. Click on a single Article
2. Then click the Cloud Icon 
3. Then choose Create in the Cloud
4. Click the cloud icon again and then choose "Update ALL" that will push to AEM Mobile the metadata, images and the .article file. 

We provide a download of the .article file as a way for someone to download the article and attach it manually, as well as diagnosing purposes. 

Thank you,
Studio Mercury

**Comment by kaynenh** [comment]
Thanks for the info. I figured something was going wrong. When I attempt to follow your steps, I get the following response. And yeah, I've tried to refresh and update and I've tried removing the article from AEM and going through the steps again. I'm reaching out to you all in a separate email/issue so we could discuss further there.

```
Failed. Could not perform action (push_entity). The version trying to update is not the latest version. Please refresh the page and try updating again. [ Show Raw Response ]

Headers
HTTP/1.1 409 Conflict
 Access-Control-Allow-Origin: *
 Access-Control-Expose-Headers: Link
 Content-Type: application/json;charset=UTF-8
 Date: Thu, 21 Apr 2016 17:57:24 GMT
 Server: APIP
 x-dps-request-id: 41b56473-b66d-4c8e-afb8-e40d33e05ac1
 Content-Length: 148
 Connection: keep-alive


Body
{"code":"VersionConflictException","message":"VersionConflictException errorCode=409 error=version conflict exception currentVersion=1461261306029"}

URL
https://pecs.publish.adobe.io/publication/d408e5cc-af88-4bcb-a613-cbad96871c27/article/promotional-sunglasses-make-a-statement;version=1461261200281
```

**Comment by StudioMercury** [comment]
A version conflict can happen because of 2 reasons: 

1) The version is out of date. You just need to refresh the page and push the change again
2) If step 1 doesn't work, the article you're trying to update has the same article name (entity name) as another article already in the AEM cloud. You will want to make sure there isn't a duplicate entity name. If there is, you can unlink the article, change the entity name and re-push the article / changes.
