### ISSUE TITLE
No return 

### ISSUE THREAD

**Issue by kandymagazine** [StudioMercury/digital-publishing-tools-for-wordpress#54]
I am attaching our .article file. When we upload to AEM and publish it is not providing the ability to return to previous. Please let us know what we can add to fix this. We had to change from .article to .zip to upload. You can change back to .article to test yourself. Thank you.

[hot-and-happening-spring-break-destinations-to-head-to.zip](https://github.com/StudioMercury/digital-publishing-tools-for-wordpress/files/220318/hot-and-happening-spring-break-destinations-to-head-to.zip)

**Comment by StudioMercury** [comment]
@kandymagazine we've reviewed this .article and it appears there are quite a bit of libraries/css that are being loaded into the .article. Inside of the AEM Mobile viewer if javascript that takes over touch gestures is included then the it prevents the AEM Mobile viewer from listening for the tap gesture. We recommend starting with our sample .article template which is confirmed working. Then add css/javascript files one by one to determine which library is causing the issue.

We've added some additional descriptions about working with templates on our new plugin homepage:
http://digitalpublishing.smny.us

Thank you
Studio Mercury
