### ISSUE TITLE
Media Temple WP Issue

### ISSUE THREAD

**Issue by kandymagazine** [StudioMercury/digital-publishing-tools-for-wordpress#55]
So we have been attempting for a couple months to get this plug in to work with no luck. So we finally signed up for the recommended WP hosting service, Media Temple.  But, we still have no luck on getting the plug in to work. We know get these error codes. We really don't know what else to do. We would hate to leave a negative review on this plugin because we know how hard it is to develop with emerging technologies but this is out third attempt on different platforms and web sites trying to get the plug in to work.

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined offset: 0 in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php on line 185

Notice: Undefined variable: sendback in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress.php on line 586

Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-content/plugins/digital-publishing/classes/cms-modules/wordpress/dpsfa-cms-wordpress-cpt-article.php:185) in /home/content/p3pnexwpnas10_data02/90/3238390/html/wp-includes/pluggable.php on line 117

**Comment by StudioMercury** [comment]
@kandymagazine, we're e-mailing you personally to get access to your installation. Please look out for an e-mail from us.

Thank you,
Mercury

**Comment by StudioMercury** [comment]
@kandymagazine, the issue above has been documented and will be fixed in the next plugin release. The issue you outlined affects batch imports of posts as articles.

**Comment by StudioMercury** [comment]
@kandymagazine  thank you for your patience. Last night we pushed an update to the plugin that brings substantial improvements to the import feature, including the ability to customize how Wordpress content is imported into AEM Mobile Articles. 

Please let us know how the new update works for you. 

Thank you,
Studio Mercury
