### ISSUE TITLE
Limit of articles? (Memory issue)

### ISSUE THREAD

**Issue by solerc** [StudioMercury/digital-publishing-tools-for-wordpress#56]
Hi.

Looking at PHP logs we found this memory problem:

> [20-Apr-2016 14:57:04 UTC] PHP Fatal error:  Allowed memory size of 94371840 bytes exhausted (tried to allocate 72 bytes) in /wp-includes/meta.php on line 838

Did you guys know about this issue? As I told you we have a lot of articles (790).

Could you help us?

Thanks.

---

Hi.

Currently we have about 790 articles and the plugin stopped to work for no reason.

We are receiving this error message: **Failed. Could not perform action (entity_list).**

Is there any limit of articles for the plugin?

Thanks.

**Comment by StudioMercury** [comment]
@solerc, this will be fixed in the next plugin update. We've e-mailed with some steps you can take in the meantime to limit the amount of articles. Please let us know if that doesn't work. 

Thank you,
Studio Mercury

**Comment by StudioMercury** [comment]
@solerc, thank you for your patience. Last night we pushed an update to the plugin that brings lazy loading to the article list view. This solves the error you were experiencing. Please let us know how the new update works for you. 

Thank you,
Studio Mercury
