### ISSUE TITLE
No response from the server

### ISSUE THREAD

**Issue by haemeulrich** [StudioMercury/digital-publishing-tools-for-wordpress#6]
((I sent the same message to "developer@smny.us))
"I'm unable to connect to the server. I get this error message:
Failed. No response from the server. Please make sure the CMS is responding.

And also this:
No publications are available. 
Please log into the DPS Portal and create at least one.

Please see also attached screenshots.

What to do?
<img width="2029" alt="bildschirmfoto 2015-09-01 um 12 25 52" src="https://cloud.githubusercontent.com/assets/7011448/9603260/ce266442-50af-11e5-8f72-a25268a8ad1a.png">
<img width="781" alt="bildschirmfoto 2015-09-01 um 12 31 25" src="https://cloud.githubusercontent.com/assets/7011448/9603261/ce282980-50af-11e5-82d7-f246d26f3f1c.png">

**Comment by Luci2015** [comment]
You are using the endpoints from stage, instead the ones from production.
try these ones:
https://ims-na1.adobelogin.com/                  Authentication server endpoints
https://authorization.publish.adobe.io/         Authorization server endpoints
https://ings.publish.adobe.io/    Ingestion server endpoints
https://pecs.publish.adobe.io/   Producer service endpoints
https://ps.publish.adobe.io/       Product service endpoints
https://publish.adobe.com/        Publish Portal

**Comment by haemeulrich** [comment]
Cool, thank you!
It is running now. I downloaded the PlugIn again – it seems that the production servers are in the current version of the Plugin. Thanks!
