### ISSUE TITLE
Failed. Could not perform action (publish_entity). One of the parameters was invalid

### ISSUE THREAD

**Issue by haemeulrich** [StudioMercury/digital-publishing-tools-for-wordpress#8]
I'm getting this error message while publishing an article to the cloud – any ideas?

Headers
HTTP/1.1 400 Bad Request
 Access-Control-Allow-Origin: *
 Access-Control-Expose-Headers: Link
 Content-Type: application/json;charset=UTF-8
 Date: Tue, 01 Sep 2015 13:35:25 GMT
 Server: APIP
 x-dps-request-id: c805cfda-554e-495b-a70f-f58caebd4912
 Content-Length: 188
 Connection: keep-alive

Body
{"code":"BadRequestException","message":"x-dps-client-request-id=28C5D11C-FF58-412B-BAC4-28671EAAC81E must match pattern=^(([0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})|([0-9a-zA-Z]{32}))$"}

URL
https://pecs.publish.adobe.io/job

**Comment by haemeulrich** [comment]
I saw that I posted a duplicate:
https://github.com/StudioMercury/digital-publishing-tools-for-wordpress/issues/2

What was the solution @josedesousa-tcc ?

**Comment by Luci2015** [comment]
I don't think it's a duplicate. Yours is a bad request 400 error type for client-request-id not of expected format =>  big letters

**Comment by haemeulrich** [comment]
Sorry I'm not a programmer. Do you have any suggestions for me based on the error?

**Comment by Luci2015** [comment]
That, Ulrich, is the money question. I have another account that gives same type of error but I could not pin point yet where this check is being done.
I'm hoping that someone from Studio Mercury might shed some light on this or provide a workaround.

**Comment by StudioMercury** [comment]
Hi guys, 

We're currently looking into this. We'll update as soon as we know more.

thank you,
Mercury

**Comment by haemeulrich** [comment]
I'm not sure if this is helpful for you: When I want to sync an article (when I'm inside the article) I get this error: Failed. No response from the server. Please make sure the CMS is responding.

**Comment by haemeulrich** [comment]
Could be that this insight is helpful for you:
https://forums.adobe.com/thread/1942601

**Comment by StudioMercury** [comment]
@haemeulrich, thank you for sending this along. We'll review it. We're currently working on it. 

Thank you for the update, 
Mercury

**Comment by haemeulrich** [comment]
Thanks I'm looking forward!

**Comment by Luci2015** [comment]
@StudioMercury  I hope you are on the right track with the analysis.
I was thinking that maybe a quick solution would be to have that "x-dps-client-request-id" generated on the 32 char format, instead of the one with dashes, as I see that this one is accepted: ([0-9a-zA-Z]{32}).
Could you look into that?

**Comment by StudioMercury** [comment]
Hi @Luci2015, thank you for this feedback, we've implemented that yesterday, we're Q/Aing the update before we push it. We hope to have it released by the end of the day.

**Comment by StudioMercury** [comment]
@Luci2015 @haemeulrich the fix has been pushed to GIT as well as the zip hosted on the plugin page. You can download the update here: http://studiomercury.github.io/digital-publishing-tools-for-wordpress/

This fix resolves the dps-client-id as well as an issue with syncing
